FROM jgoldfar/fenics:base as base
LABEL maintainer="Jonathan Goldfarb <jgoldfar@my.fit.edu>"
USER root
WORKDIR /home/fenics/shared

FROM base as nbconvert
ENTRYPOINT ["jupyter-nbconvert"]

FROM base as jupyter
ENTRYPOINT ["jupyter-notebook"]
CMD ["--ip=0.0.0.0", "--allow-root"]
